### ISSUE TITLE
Page not reloaded or script not triggered after cookies accept

### ISSUE THREAD

**Issue by frobert** [jazzband/django-cookie-consent#113]
Hi there, we are having an issue with triggering the sciprts after cookie consent was accepted.

in the tamplete we have a code 
```
{% if request|cookie_group_accepted:"optional" %}
<script>
  dataLayer.push({
    event: 'cookies_consent',
  });
</script>
{% endif %}
```

that should trigger the event after the cookies are confirmed, but after confirming nothing is happening, the script is not triggered nor the page is reloaded... The script is triggered after manually reloading the page.

please advice...

thanks

**Comment by some1ataplace** [comment]
I thought the same thing, which is why I made this PR but it got rejected. 

https://github.com/jazzband/django-cookie-consent/pull/71

**Comment by sergei-maertens** [comment]
There is some documentation for this case available already: https://django-cookie-consent.readthedocs.io/en/latest/javascript.html#enabling-other-scripts-after-cookies-were-accepted

Please let me know if this works for you or not, and if the documentation can be improved, that would also be great of course!

**Comment by sergei-maertens** [comment]
Version 0.6.0 includes the improved Javascript integration, which should help address this issue. As mentioned above, there is already documentation as well for how to approach this.
