### ISSUE TITLE
Docs have blank sections

### ISSUE THREAD

**Issue by 9mido** [jazzband/django-cookie-consent#14]
The API documentation section is blank in the docs. Is that because these things are planned and are not available yet? 

https://django-cookie-consent.readthedocs.io/en/latest/api_models.html

https://django-cookie-consent.readthedocs.io/en/latest/api_views.html

https://django-cookie-consent.readthedocs.io/en/latest/api_util.html

https://django-cookie-consent.readthedocs.io/en/latest/api_templatetags.html

https://django-cookie-consent.readthedocs.io/en/latest/api_middleware.html

**Comment by bmihelac** [comment]
@9mido no, I guess that there is some misconfiguration. PR would be welcomed :)

**Comment by 9mido** [comment]
@bmihelac I am not much of a programmer I am more of a bug finder so I wouldn't have much insight into making a PR for this. Hopefully someone else could though!

**Comment by some1ataplace** [comment]
If anyone knows how to read/write restructured text language or use sphinx then that would help resolve this issue. 

So far this is what I have done:

Download a zip file of django-cookie-consent
```
cd ~/downloads/django-cookie-consent-master/docs
sudo apt install sphinx-doc sphinx-common
make html
```

Inside of docs conf.py:
```
import django
sys.path.insert(0, os.path.abspath(os.path.join('..', '..', 'cookie_consent')))
os.environ['DJANGO_SETTINGS_MODULE'] = 'settings'
django.setup()
```
