### ISSUE TITLE
How can i set cookie on root domain?

### ISSUE THREAD

**Issue by VictorGerritsen** [jazzband/django-cookie-consent#36]
Is there a way to set the cookie-consent cookie on the root domain? e.g. `*.mydomain.com`  I have a wildcard subdomain and right now the consent cookie includes the subdomain, making the consent banner popup appear for each subdomain i visit.

**Comment by 9mido** [comment]
@VictorGerritsen 

Just to be clear, you only want have the cookie consent banner show up on only the root domain and not the subdomains? 

Example only show it on mydomain.com and do not show it on sub.mydomain.com ?

**Comment by some1ataplace** [comment]
Some research:

https://stackoverflow.com/questions/3742675/sharing-django-sessions-on-specific-subdomains

https://stackoverflow.com/questions/556907/how-to-get-distinct-django-apps-on-same-subdomain-to-share-session-cookie

https://stackoverflow.com/questions/18492576/share-cookie-between-subdomain-and-domain

https://serverfault.com/questions/153409/can-subdomain-example-com-set-a-cookie-that-can-be-read-by-example-com

https://stackoverflow.com/questions/2116860/django-session-cookie-domain-with-multiple-domains

https://stackoverflow.com/questions/53349940/cookie-behavior-in-django

https://stackoverflow.com/questions/2043138/could-not-get-cookie-from-another-parent-domain-in-django

https://stackoverflow.com/questions/5258126/domain-set-cookie-for-subdomain

https://stackoverflow.com/questions/5671451/creating-a-javascript-cookie-on-a-domain-and-reading-it-across-sub-domains

https://stackoverflow.com/questions/4713019/setting-cross-subdomain-cookie-with-javascript
