### ISSUE TITLE
when declined the bar shows up at next page loading

### ISSUE THREAD

**Issue by qkral** [jazzband/django-cookie-consent#46]
Is there a specific set-up for preventing the cookie bar to show up again when reloading the page even though it had been declined? or is it normal behaviour?

To reproduce:
Step 1) I load the home page and I click Decline on the cookie bar
Step 2) I reload the home page and the cookie bar shows up again, which I would like to prevent

**Comment by bmihelac** [comment]
@qkral thanks for reporting. I cannot reproduce this issue on example application. After clicking on "Decline" button and reloading page, I do not see cookie bar, screenshot:

![2021-12-09_09-15](https://user-images.githubusercontent.com/13813/145359265-76f91251-b3de-469d-906f-0e03b2d0cd99.png)


From developer tools I see following cookie:
`cookie_consent=social=-1|optional=-1`

**Comment by some1ataplace** [comment]
@qkral You might be using an older version of django-cookie-consent. Please update the a more recent version and try again.

**Comment by sergei-maertens** [comment]
@qkral - does this issue still happen (on the latest version) and can you provide steps on how to reproduce this?

**Comment by sergei-maertens** [comment]
django-cookie-consent 0.4.0 is now on PyPI. Please reopen this issue if this problem still happens after upgrading.
