### ISSUE TITLE
Required config line missing in documentation

### ISSUE THREAD

**Issue by saint-hilaire** [jazzband/django-cookie-consent#68]
I had some trouble setting up this app in my project, until I realized that in my `settings.py` I need the to set the `COOKIE_CONSENT_NAME` variable. That is, I added the following line:
```
COOKIE_CONSENT_NAME = "cookie_consent"
```

This step does seem rather important, but I didn't see it mentioned anywhere in the docs for setting up, specifically here: https://django-cookie-consent.readthedocs.io/en/latest/configuration.html.

I figured, this is the best place to let someone know ;-)

**Comment by some1ataplace** [comment]
Added this via PR #69

**Comment by sergei-maertens** [comment]
This has been fixed in master - the 0.4.0 release will no longer require this setting to be set explicitly.
