### ISSUE TITLE
SuccessURLAllowedHostsMixin is replaced by RedirectURLMixin in Django 4.1

### ISSUE THREAD

**Issue by jirkasimonek** [jazzband/django-cookie-consent#87]
Hi, I've just install django-cookie-consent for Django 4.1 a I've got an error: "cannot import name 'SuccessURLAllowedHostsMixin' from 'django.contrib.auth.views'" 

In Django 4.1 'SuccessURLAllowedHostsMixin'  is replaced by 'RedirectURLMixin' - see following release notes https://docs.djangoproject.com/en/4.1/releases/4.1/

I've just solved it by replacing line 3 in cookie_consent/views.py 
from django.contrib.auth.views import RedirectURLMixin as SuccessURLAllowedHostsMixin

So at least such a change is necessary to make it work for Django 4.1

**Comment by spechtx** [comment]
Thank you very much for your post. That worked perfectly for me.

**Comment by sergei-maertens** [comment]
Sweet, I was about to start work on confirming/adding support for Django 4.1 and 4.2, with the latter being released a month ago and being an LTS release.

**Comment by sergei-maertens** [comment]
Looks like this was addressed in 54f5e5fae0b5d94e34d09385b5e4cd87d5e2c6a6 already, unfortunately I am not able to release a new version to PyPI at the moment, see https://github.com/jazzband/help/issues/337
