### ISSUE TITLE
Compatibility Issue with django-cookie-consent 0.3.1 and Django 4.2.2

### ISSUE THREAD

**Issue by CurtMRosenblad** [jazzband/django-cookie-consent#94]
## Issue Description

I am encountering an `ImportError` while trying to use the `django-cookie-consent` package with Django 4.2.2. The specific error message I receive is as follows:

ImportError: cannot import name 'SuccessURLAllowedHostsMixin' from 'django.contrib.auth.views'

## Steps to Reproduce

1. Install Django 4.2.2.
2. Install the latest version of `django-cookie-consent` (0.3.1).
3. Followed the installation instructions mentioned in the documentation.
4. Run the `migrate` command.

## Expected Behavior

The `migrate` command should run successfully without any import errors.

## Actual Behavior

The `migrate` command fails with the `ImportError` mentioned above.

## Environment

- Django version: 4.2.2
- `django-cookie-consent` version: 0.3.1

## Additional Information

I have checked that I am using the latest version of `django-cookie-consent`, and I have confirmed that Django 4.2.2 does include the `SuccessURLAllowedHostsMixin` in the `django.contrib.auth.views` module.

Please let me know if there are any compatibility fixes or workarounds available for this issue. Thank you.

**Comment by sergei-maertens** [comment]
Hi @CurtMRosenblad, thanks for reporting this problem. It has been patched and made available as a pre-release on PyPI, which is why the latest version is still showing as 0.3.1

I've just ticked off the last item blocking the full 0.4.0 release, so that version will become available momentarily.

**Comment by sergei-maertens** [comment]
django-cookie-consent 0.4.0 is now on PyPI!
